id = "zada-theme"
name = "Zada Theme"
version = "1.1.0"
schema_version = 1
authors = ["zadaziri <zdzirin@gmail.com>"]
description = "Personal Zed theme forked from blaqat's Tomorrow Theme Zed, which is in turn based on chriskempson's Tomorrow Theme, VS Code's Tomorrow Night Blue, and mdBook's Coal Theme"
repository = "https://github.com/zdzirin/zada-theme-zed"
